name: Build Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: MilesChou/composer-action@master
        with:
          args: install 
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: '.github/release.zip'
          exclusions: '*.git* build'
      - name: Git Release
        uses: anton-yurchenko/git-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
        with:
          args: |
            .github/release.zip
